language: rust

services:
  - docker

rust:
  - nightly
before_script:
  - cd quick-install/self-cert && ./make-certs.sh && cd ../.. 
  - mkdir certs && cp quick-install/self-cert/domain.crt ./certs/ 
  - cp quick-install/self-cert/domain.key ./certs/
  - rustup default nightly-2020-02-07 && rustup component add rustfmt 
  - cargo update
  - export VCS_REF=$(git rev-parse HEAD)
script:
  - cargo build --verbose --all
  - cd lib/server && cargo test --verbose && cd ../..
  - cargo test --verbose --all
  - cargo test --verbose -- --ignored
addons:
  hosts:
    - trow.test
notifications:
  slack:
    rooms:
      secure: fETDT1QQGUjprGPWOanI9msQJtX9a2XTfW2E+13NCinXvigz2830VfdU09WtPhLMMVaRJgUYvRnyUbzyH+9KWCWMuXritzAKtqRNMfKkp5zbXGQyKc7yTDzLYZLq3VZzOsGEYRbxM1+yU0dmVRVqFca0hm9SE+V6+2Ry4KT+tTGZYvGbHJ1JmUd4ixJvFS5ziD4zrca0Ne1KvWDyMumsfUZCW0wphMZsuve95/WUx1WJINh83qevzijWV7Y+00fP2idY3m0eSVZJTwvTr519D9XKYSsDEPf7qvXFCiY7R7d6YrryJ5oRGef1+d+aJqsXjduFnagHLoPqXx/EzlRVmZ1hddGElTOVNZ4AVea4icZQr2uwLyPxMoyoOkaOam9freTkw9ng54NsXVBgcc4zBXdytO3adaT+ULeDtDCDgkjpEHM0kOWUFRFWtkb+leBjk9bgU9E0ZEkuvEzP20BOApFeO7k4PSEx3zSMH5l73D6y04VtmhWSv0AkxiIagERiBxBLGGHAxmFUurVYgY0Najrpqvz2zIMltvJDmLNyzv5d1r/QQpHSt9frZgF8lcR6c7NLf4/7bz8CHknjPKfOSnTaQCDjnKc6K4EBLoELpgScmacI+b3gPlqUbR9Dm12Y+vSYzEllBK6pGhUDkhXUeRThU2WA5nkI2BaQ2gFW18c=
    on_success: change
    on_failure: always
