apiVersion: v2
name: trow
description: Helm chart for Trow registry
type: application
home: https://trow.io
kubeVersion: ">= 1.26.0-0"
maintainers:
  - name: awoimbee
    url: https://github.com/awoimbee

version: 0.12.3
appVersion: 0.9.3
