apiVersion: apps/v1
kind: Deployment
metadata:
  name: trow-deploy
spec:
  selector:
    matchLabels:
      app: trow
  template:
    metadata:
      labels:
        app: trow
    spec:
      containers:
      - name: trow-pod
        image: containersol/trow:0.3
        args: 
          - "--no-tls" 
          - "-n" 
          - "myregistry.mydomain.io" 
          - "-u" 
          - "myuser" 
          - "--password-file" 
          - "/etc/trow/pass"
        imagePullPolicy: Always
        ports:
        - name: trow-http-port
          containerPort: 8000
        volumeMounts:
        - name: data-vol
          mountPath: /data
        - name: trow-pass
          mountPath: /etc/trow
          readOnly: true
      volumes:
        - name: trow-pass
          secret:
            secretName: trow-pass
            items:
              - key: pass
                path: pass
        - name: data-vol
          emptyDir: {}
      securityContext:             
        runAsUser: 333333
        runAsGroup: 333333
        fsGroup: 333333
