apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trow-test

# This configuration assumes your cluster has cert-manager configured and is using nginx for
# ingress.

bases:
    - ../../base

resources:
    - cert.yaml # Update with domain for your registry
    - trow-ingress.yaml
