image:
  repository: trow
  tag: onpr
trow:
  domain: "127.0.0.1"
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
  hosts:
    - paths: ['/']
      host: "none"
webhooks:
  replicas: 1
  namespaceSelector:
    matchLabels:
      example.com/kind: "proxied"
