apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-server
  namespace: spire
  labels:
    app: spire-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  template:
    metadata:
      namespace: spire
      labels:
        app: spire-server
    spec:
      serviceAccountName: spire-server
      containers:
      - name: spire-server
        image: gcr.io/spiffe-io/spire-server:0.11.0
        args: ["-config", "/run/spire/config/server.conf"]
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: spire-config
          readOnly: true
          mountPath: /run/spire/config
        - name: spire-secrets
          readOnly: true
          mountPath: /run/spire/secrets
        livenessProbe:
          exec:
            command: ["/opt/spire/bin/spire-server", "healthcheck"]
          failureThreshold: 2
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 3
        readinessProbe:
          exec:
            command: ["/opt/spire/bin/spire-server", "healthcheck", "--shallow"]
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: spire-config
        configMap:
          name: spire-server
      - name: spire-secrets
        secret:
          secretName: spire-server
