apiVersion: v1
kind: Service
metadata:
  name: trow-svc
spec:
  selector:
    app: trow
  type: NodePort
  ports:
  - name: http-tcp
    protocol: TCP
    port: 8000
    targetPort: trow-http-port
  - name: https-tcp
    protocol: TCP
    port: 8443
    targetPort: trow-https-port

