name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        default: true
        components: rustfmt
    - name: Install certs
      run: |
        cd quick-install/self-cert && ./make-certs.sh && cd ../..
        mkdir certs
        cp quick-install/self-cert/domain.crt ./certs/
        cp quick-install/self-cert/domain.key ./certs/
    - name: Add trow.test to hosts
      run: |
        echo "127.0.0.1 trow.test" | sudo tee -a /etc/hosts  
    - name: Check trow.test is accessible
      run: |
          ping -c 1 trow.test
    - name: Run Cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --all
    - name: Run server lib test suite
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --manifest-path=lib/server/Cargo.toml
    - name: Check formatting
      run:  cargo fmt -- --check
    - name: Run Trow test suite
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --all -- --test-threads=1
    - name: Smoke test
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose -- --ignored
      
      
